/**
 * SISPAGER-GRD - Peru Locations Database
 * Generated automatically from Ubigeo.csv (official)
 */

export const LOCATIONS = {
  "AMAZONAS": {
    "BAGUA": [
      "ARAMANGO",
      "BAGUA",
      "COPALLIN",
      "EL PARCO",
      "IMAZA",
      "LA PECA"
    ],
    "BONGARA": [
      "CHISQUILLA",
      "CHURUJA",
      "COROSHA",
      "CUISPES",
      "FLORIDA",
      "JAZAN",
      "JUMBILLA",
      "RECTA",
      "SAN CARLOS",
      "SHIPASBAMBA",
      "VALERA",
      "YAMBRASBAMBA"
    ],
    "CHACHAPOYAS": [
      "ASUNCION",
      "BALSAS",
      "CHACHAPOYAS",
      "CHETO",
      "CHILIQUIN",
      "CHUQUIBAMBA",
      "GRANADA",
      "HUANCAS",
      "LA JALCA",
      "LEIMEBAMBA",
      "LEVANTO",
      "MAGDALENA",
      "MARISCAL CASTILLA",
      "MOLINOPAMPA",
      "MONTEVIDEO",
      "OLLEROS",
      "QUINJALCA",
      "SAN FRANCISCO DE DAGUAS",
      "SAN ISIDRO DE MAINO",
      "SOLOCO",
      "SONCHE"
    ],
    "CONDORCANQUI": [
      "EL CENEPA",
      "NIEVA",
      "RIO SANTIAGO"
    ],
    "LUYA": [
      "CAMPORREDONDO",
      "COCABAMBA",
      "COLCAMAR",
      "CONILA",
      "INGUILPATA",
      "LAMUD",
      "LONGUITA",
      "LONYA CHICO",
      "LUYA",
      "LUYA VIEJO",
      "MARIA",
      "OCALLI",
      "OCUMAL",
      "PISUQUIA",
      "PROVIDENCIA",
      "SAN CRISTOBAL",
      "SAN FRANCISCO DEL YESO",
      "SAN JERONIMO",
      "SAN JUAN DE LOPECANCHA",
      "SANTA CATALINA",
      "SANTO TOMAS",
      "TINGO",
      "TRITA"
    ],
    "RODRIGUEZ DE MENDOZA": [
      "CHIRIMOTO",
      "COCHAMAL",
      "HUAMBO",
      "LIMABAMBA",
      "LONGAR",
      "MARISCAL BENAVIDES",
      "MILPUC",
      "OMIA",
      "SAN NICOLAS",
      "SANTA ROSA",
      "TOTORA",
      "VISTA ALEGRE"
    ],
    "UTCUBAMBA": [
      "BAGUA GRANDE",
      "CAJARURO",
      "CUMBA",
      "EL MILAGRO",
      "JAMALCA",
      "LONYA GRANDE",
      "YAMON"
    ]
  },
  "ANCASH": {
    "AIJA": [
      "AIJA",
      "CORIS",
      "HUACLLAN",
      "LA MERCED",
      "SUCCHA"
    ],
    "ANTONIO RAYMONDI": [
      "ACZO",
      "CHACCHO",
      "CHINGAS",
      "LLAMELLIN",
      "MIRGAS",
      "SAN JUAN DE RONTOY"
    ],
    "ASUNCION": [
      "ACOCHACA",
      "CHACAS"
    ],
    "BOLOGNESI": [
      "ABELARDO PARDO LEZAMETA",
      "ANTONIO RAYMONDI",
      "AQUIA",
      "CAJACAY",
      "CANIS",
      "CHIQUIAN",
      "COLQUIOC",
      "HUALLANCA",
      "HUASTA",
      "HUAYLLACAYAN",
      "LA PRIMAVERA",
      "MANGAS",
      "PACLLON",
      "SAN MIGUEL DE CORPANQUI",
      "TICLLOS"
    ],
    "CARHUAZ": [
      "ACOPAMPA",
      "AMASHCA",
      "ANTA",
      "ATAQUERO",
      "CARHUAZ",
      "MARCARA",
      "PARIAHUANCA",
      "SAN MIGUEL DE ACO",
      "SHILLA",
      "TINCO",
      "YUNGAR"
    ],
    "CARLOS FERMIN FITZCARRALD": [
      "SAN LUIS",
      "SAN NICOLAS",
      "YAUYA"
    ],
    "CASMA": [
      "BUENA VISTA ALTA",
      "CASMA",
      "COMANDANTE NOEL",
      "YAUTAN"
    ],
    "CORONGO": [
      "ACO",
      "BAMBAS",
      "CORONGO",
      "CUSCA",
      "LA PAMPA",
      "YANAC",
      "YUPAN"
    ],
    "HUARAZ": [
      "COCHABAMBA",
      "COLCABAMBA",
      "HUANCHAY",
      "HUARAZ",
      "INDEPENDENCIA",
      "JANGAS",
      "LA LIBERTAD",
      "OLLEROS",
      "PAMPAS",
      "PARIACOTO",
      "PIRA",
      "TARICA"
    ],
    "HUARI": [
      "ANRA",
      "CAJAY",
      "CHAVIN DE HUANTAR",
      "HUACACHI",
      "HUACCHIS",
      "HUACHIS",
      "HUANTAR",
      "HUARI",
      "MASIN",
      "PAUCAS",
      "PONTO",
      "RAHUAPAMPA",
      "RAPAYAN",
      "SAN MARCOS",
      "SAN PEDRO DE CHANA",
      "UCO"
    ],
    "HUARMEY": [
      "COCHAPETI",
      "CULEBRAS",
      "HUARMEY",
      "HUAYAN",
      "MALVAS"
    ],
    "HUAYLAS": [
      "CARAZ",
      "HUALLANCA",
      "HUATA",
      "HUAYLAS",
      "MATO",
      "PAMPAROMAS",
      "PUEBLO LIBRE",
      "SANTA CRUZ",
      "SANTO TORIBIO",
      "YURACMARCA"
    ],
    "MARISCAL LUZURIAGA": [
      "CASCA",
      "ELEAZAR GUZMAN BARRON",
      "FIDEL OLIVAS ESCUDERO",
      "LLAMA",
      "LLUMPA",
      "LUCMA",
      "MUSGA",
      "PISCOBAMBA"
    ],
    "OCROS": [
      "ACAS",
      "CAJAMARQUILLA",
      "CARHUAPAMPA",
      "COCHAS",
      "CONGAS",
      "LLIPA",
      "OCROS",
      "SAN CRISTOBAL DE RAJAN",
      "SAN PEDRO",
      "SANTIAGO DE CHILCAS"
    ],
    "PALLASCA": [
      "BOLOGNESI",
      "CABANA",
      "CONCHUCOS",
      "HUACASCHUQUE",
      "HUANDOVAL",
      "LACABAMBA",
      "LLAPO",
      "PALLASCA",
      "PAMPAS",
      "SANTA ROSA",
      "TAUCA"
    ],
    "POMABAMBA": [
      "HUAYLLAN",
      "PAROBAMBA",
      "POMABAMBA",
      "QUINUABAMBA"
    ],
    "RECUAY": [
      "CATAC",
      "COTAPARACO",
      "HUAYLLAPAMPA",
      "LLACLLIN",
      "MARCA",
      "PAMPAS CHICO",
      "PARARIN",
      "RECUAY",
      "TAPACOCHA",
      "TICAPAMPA"
    ],
    "SANTA": [
      "CACERES DEL PERU",
      "CHIMBOTE",
      "COISHCO",
      "MACATE",
      "MORO",
      "NEPEÑA",
      "NUEVO CHIMBOTE",
      "SAMANCO",
      "SANTA"
    ],
    "SIHUAS": [
      "ACOBAMBA",
      "ALFONSO UGARTE",
      "CASHAPAMPA",
      "CHINGALPO",
      "HUAYLLABAMBA",
      "QUICHES",
      "RAGASH",
      "SAN JUAN",
      "SICSIBAMBA",
      "SIHUAS"
    ],
    "YUNGAY": [
      "CASCAPARA",
      "MANCOS",
      "MATACOTO",
      "QUILLO",
      "RANRAHIRCA",
      "SHUPLUY",
      "YANAMA",
      "YUNGAY"
    ]
  },
  "APURIMAC": {
    "ABANCAY": [
      "ABANCAY",
      "CHACOCHE",
      "CIRCA",
      "CURAHUASI",
      "HUANIPACA",
      "LAMBRAMA",
      "PICHIRHUA",
      "SAN PEDRO DE CACHORA",
      "TAMBURCO"
    ],
    "ANDAHUAYLAS": [
      "ANDAHUAYLAS",
      "ANDARAPA",
      "CHIARA",
      "HUANCARAMA",
      "HUANCARAY",
      "HUAYANA",
      "JOSE MARIA ARGUEDAS",
      "KAQUIABAMBA",
      "KISHUARA",
      "PACOBAMBA",
      "PACUCHA",
      "PAMPACHIRI",
      "POMACOCHA",
      "SAN ANTONIO DE CACHI",
      "SAN JERONIMO",
      "SAN MIGUEL DE CHACCRAMPA",
      "SANTA MARIA DE CHICMO",
      "TALAVERA",
      "TUMAY HUARACA",
      "TURPO"
    ],
    "ANTABAMBA": [
      "ANTABAMBA",
      "EL ORO",
      "HUAQUIRCA",
      "JUAN ESPINOZA MEDRANO",
      "OROPESA",
      "PACHACONAS",
      "SABAINO"
    ],
    "AYMARAES": [
      "CAPAYA",
      "CARAYBAMBA",
      "CHALHUANCA",
      "CHAPIMARCA",
      "COLCABAMBA",
      "COTARUSE",
      "HUAYLLO",
      "JUSTO APU SAHUARAURA",
      "LUCRE",
      "POCOHUANCA",
      "SAN JUAN DE CHACÑA",
      "SAÑAYCA",
      "SORAYA",
      "TAPAIRIHUA",
      "TINTAY",
      "TORAYA",
      "YANACA"
    ],
    "CHINCHEROS": [
      "AHUAYRO",
      "ANCO-HUALLO",
      "CHINCHEROS",
      "COCHARCAS",
      "EL PORVENIR",
      "HUACCANA",
      "LOS CHANKAS",
      "OCOBAMBA",
      "ONGOY",
      "RANRACANCHA",
      "ROCCHACC",
      "URANMARCA"
    ],
    "COTABAMBAS": [
      "CHALLHUAHUACHO",
      "COTABAMBAS",
      "COYLLURQUI",
      "HAQUIRA",
      "MARA",
      "TAMBOBAMBA"
    ],
    "GRAU": [
      "CHUQUIBAMBILLA",
      "CURASCO",
      "CURPAHUASI",
      "GAMARRA",
      "HUAYLLATI",
      "MAMARA",
      "MICAELA BASTIDAS",
      "PATAYPAMPA",
      "PROGRESO",
      "SAN ANTONIO",
      "SANTA ROSA",
      "TURPAY",
      "VILCABAMBA",
      "VIRUNDO"
    ]
  },
  "AREQUIPA": {
    "AREQUIPA": [
      "ALTO SELVA ALEGRE",
      "AREQUIPA",
      "CAYMA",
      "CERRO COLORADO",
      "CHARACATO",
      "CHIGUATA",
      "JACOBO HUNTER",
      "JOSE LUIS BUSTAMANTE Y RIVERO",
      "LA JOYA",
      "MARIANO MELGAR",
      "MIRAFLORES",
      "MOLLEBAYA",
      "PAUCARPATA",
      "POCSI",
      "POLOBAYA",
      "QUEQUEÑA",
      "SABANDIA",
      "SACHACA",
      "SAN JUAN DE SIGUAS",
      "SAN JUAN DE TARUCANI",
      "SANTA ISABEL DE SIGUAS",
      "SANTA RITA DE SIGUAS",
      "SOCABAYA",
      "TIABAYA",
      "UCHUMAYO",
      "VITOR",
      "YANAHUARA",
      "YARABAMBA",
      "YURA"
    ],
    "CAMANA": [
      "CAMANA",
      "JOSE MARIA QUIMPER",
      "MARIANO NICOLAS VALCARCEL",
      "MARISCAL CACERES",
      "NICOLAS DE PIEROLA",
      "OCOÑA",
      "QUILCA",
      "SAMUEL PASTOR"
    ],
    "CARAVELI": [
      "ACARI",
      "ATICO",
      "ATIQUIPA",
      "BELLA UNION",
      "CAHUACHO",
      "CARAVELI",
      "CHALA",
      "CHAPARRA",
      "HUANUHUANU",
      "JAQUI",
      "LOMAS",
      "QUICACHA",
      "YAUCA"
    ],
    "CASTILLA": [
      "ANDAGUA",
      "APLAO",
      "AYO",
      "CHACHAS",
      "CHILCAYMARCA",
      "CHOCO",
      "HUANCARQUI",
      "MACHAGUAY",
      "ORCOPAMPA",
      "PAMPACOLCA",
      "TIPAN",
      "URACA",
      "UÑON",
      "VIRACO"
    ],
    "CAYLLOMA": [
      "ACHOMA",
      "CABANACONDE",
      "CALLALLI",
      "CAYLLOMA",
      "CHIVAY",
      "COPORAQUE",
      "HUAMBO",
      "HUANCA",
      "ICHUPAMPA",
      "LARI",
      "LLUTA",
      "MACA",
      "MADRIGAL",
      "MAJES",
      "SAN ANTONIO DE CHUCA",
      "SIBAYO",
      "TAPAY",
      "TISCO",
      "TUTI",
      "YANQUE"
    ],
    "CONDESUYOS": [
      "ANDARAY",
      "CAYARANI",
      "CHICHAS",
      "CHUQUIBAMBA",
      "IRAY",
      "RIO GRANDE",
      "SALAMANCA",
      "YANAQUIHUA"
    ],
    "ISLAY": [
      "COCACHACRA",
      "DEAN VALDIVIA",
      "ISLAY",
      "MEJIA",
      "MOLLENDO",
      "PUNTA DE BOMBON"
    ],
    "LA UNION": [
      "ALCA",
      "CHARCANA",
      "COTAHUASI",
      "HUAYNACOTAS",
      "PAMPAMARCA",
      "PUYCA",
      "QUECHUALLA",
      "SAYLA",
      "TAURIA",
      "TOMEPAMPA",
      "TORO"
    ]
  },
  "AYACUCHO": {
    "CANGALLO": [
      "CANGALLO",
      "CHUSCHI",
      "LOS MOROCHUCOS",
      "MARIA PARADO DE BELLIDO",
      "PARAS",
      "TOTOS"
    ],
    "HUAMANGA": [
      "ACOCRO",
      "ACOS VINCHOS",
      "ANDRES AVELINO CACERES DORREGARAY",
      "AYACUCHO",
      "CARMEN ALTO",
      "CHIARA",
      "JESUS NAZARENO",
      "OCROS",
      "PACAYCASA",
      "QUINUA",
      "SAN JOSE DE TICLLAS",
      "SAN JUAN BAUTISTA",
      "SANTIAGO DE PISCHA",
      "SOCOS",
      "TAMBILLO",
      "VINCHOS"
    ],
    "HUANCA SANCOS": [
      "CARAPO",
      "SACSAMARCA",
      "SANCOS",
      "SANTIAGO DE LUCANAMARCA"
    ],
    "HUANTA": [
      "AYAHUANCO",
      "CANAYRE",
      "CHACA",
      "HUAMANGUILLA",
      "HUANTA",
      "IGUAIN",
      "LLOCHEGUA",
      "LURICOCHA",
      "PUCACOLPA",
      "PUTIS",
      "SANTILLANA",
      "SIVIA",
      "UCHURACCAY"
    ],
    "LA MAR": [
      "ANCHIHUAY",
      "ANCO",
      "AYNA",
      "CHILCAS",
      "CHUNGUI",
      "LUIS CARRANZA",
      "NINABAMBA",
      "ORONCCOY",
      "PATIBAMBA",
      "RIO MAGDALENA",
      "SAMUGARI",
      "SAN MIGUEL",
      "SANTA ROSA",
      "TAMBO",
      "UNION PROGRESO"
    ],
    "LUCANAS": [
      "AUCARA",
      "CABANA",
      "CARMEN SALCEDO",
      "CHAVIÑA",
      "CHIPAO",
      "HUAC-HUAS",
      "LARAMATE",
      "LEONCIO PRADO",
      "LLAUTA",
      "LUCANAS",
      "OCAÑA",
      "OTOCA",
      "PUQUIO",
      "SAISA",
      "SAN CRISTOBAL",
      "SAN JUAN",
      "SAN PEDRO",
      "SAN PEDRO DE PALCO",
      "SANCOS",
      "SANTA ANA DE HUAYCAHUACHO",
      "SANTA LUCIA"
    ],
    "PARINACOCHAS": [
      "CHUMPI",
      "CORACORA",
      "CORONEL CASTAÑEDA",
      "PACAPAUSA",
      "PULLO",
      "PUYUSCA",
      "SAN FRANCISCO DE RAVACAYCO",
      "UPAHUACHO"
    ],
    "PAUCAR DEL SARA SARA": [
      "COLTA",
      "CORCULLA",
      "LAMPA",
      "MARCABAMBA",
      "OYOLO",
      "PARARCA",
      "PAUSA",
      "SAN JAVIER DE ALPABAMBA",
      "SAN JOSE DE USHUA",
      "SARA SARA"
    ],
    "SUCRE": [
      "BELEN",
      "CHALCOS",
      "CHILCAYOC",
      "HUACAÑA",
      "MORCOLLA",
      "PAICO",
      "QUEROBAMBA",
      "SAN PEDRO DE LARCAY",
      "SAN SALVADOR DE QUIJE",
      "SANTIAGO DE PAUCARAY",
      "SORAS"
    ],
    "VICTOR FAJARDO": [
      "ALCAMENCA",
      "APONGO",
      "ASQUIPATA",
      "CANARIA",
      "CAYARA",
      "COLCA",
      "HUAMANQUIQUIA",
      "HUANCAPI",
      "HUANCARAYLLA",
      "HUAYA",
      "SARHUA",
      "VILCANCHOS"
    ],
    "VILCAS HUAMAN": [
      "ACCOMARCA",
      "CARHUANCA",
      "CONCEPCION",
      "HUAMBALPA",
      "INDEPENDENCIA",
      "SAURAMA",
      "VILCAS HUAMAN",
      "VISCHONGO"
    ]
  },
  "CAJAMARCA": {
    "CAJABAMBA": [
      "CACHACHI",
      "CAJABAMBA",
      "CONDEBAMBA",
      "SITACOCHA"
    ],
    "CAJAMARCA": [
      "ASUNCION",
      "CAJAMARCA",
      "CHETILLA",
      "COSPAN",
      "ENCAÑADA",
      "JESUS",
      "LLACANORA",
      "LOS BAÑOS DEL INCA",
      "MAGDALENA",
      "MATARA",
      "NAMORA",
      "SAN JUAN"
    ],
    "CELENDIN": [
      "CELENDIN",
      "CHUMUCH",
      "CORTEGANA",
      "HUASMIN",
      "JORGE CHAVEZ",
      "JOSE GALVEZ",
      "LA LIBERTAD DE PALLAN",
      "MIGUEL IGLESIAS",
      "OXAMARCA",
      "SOROCHUCO",
      "SUCRE",
      "UTCO"
    ],
    "CHOTA": [
      "ANGUIA",
      "CHADIN",
      "CHALAMARCA",
      "CHIGUIRIP",
      "CHIMBAN",
      "CHOROPAMPA",
      "CHOTA",
      "COCHABAMBA",
      "CONCHAN",
      "HUAMBOS",
      "LAJAS",
      "LLAMA",
      "MIRACOSTA",
      "PACCHA",
      "PION",
      "QUEROCOTO",
      "SAN JUAN DE LICUPIS",
      "TACABAMBA",
      "TOCMOCHE"
    ],
    "CONTUMAZA": [
      "CHILETE",
      "CONTUMAZA",
      "CUPISNIQUE",
      "GUZMANGO",
      "SAN BENITO",
      "SANTA CRUZ DE TOLEDO",
      "TANTARICA",
      "YONAN"
    ],
    "CUTERVO": [
      "CALLAYUC",
      "CHOROS",
      "CUJILLO",
      "CUTERVO",
      "LA RAMADA",
      "PIMPINGOS",
      "QUEROCOTILLO",
      "SAN ANDRES DE CUTERVO",
      "SAN JUAN DE CUTERVO",
      "SAN LUIS DE LUCMA",
      "SANTA CRUZ",
      "SANTO DOMINGO DE LA CAPILLA",
      "SANTO TOMAS",
      "SOCOTA",
      "TORIBIO CASANOVA"
    ],
    "HUALGAYOC": [
      "BAMBAMARCA",
      "CHUGUR",
      "HUALGAYOC"
    ],
    "JAEN": [
      "BELLAVISTA",
      "CHONTALI",
      "COLASAY",
      "HUABAL",
      "JAEN",
      "LAS PIRIAS",
      "POMAHUACA",
      "PUCARA",
      "SALLIQUE",
      "SAN FELIPE",
      "SAN JOSE DEL ALTO",
      "SANTA ROSA"
    ],
    "SAN IGNACIO": [
      "CHIRINOS",
      "HUARANGO",
      "LA COIPA",
      "NAMBALLE",
      "SAN IGNACIO",
      "SAN JOSE DE LOURDES",
      "TABACONAS"
    ],
    "SAN MARCOS": [
      "CHANCAY",
      "EDUARDO VILLANUEVA",
      "GREGORIO PITA",
      "ICHOCAN",
      "JOSE MANUEL QUIROZ",
      "JOSE SABOGAL",
      "PEDRO GALVEZ"
    ],
    "SAN MIGUEL": [
      "BOLIVAR",
      "CALQUIS",
      "CATILLUC",
      "EL PRADO",
      "LA FLORIDA",
      "LLAPA",
      "NANCHOC",
      "NIEPOS",
      "SAN GREGORIO",
      "SAN MIGUEL",
      "SAN SILVESTRE DE COCHAN",
      "TONGOD",
      "UNION AGUA BLANCA"
    ],
    "SAN PABLO": [
      "SAN BERNARDINO",
      "SAN LUIS",
      "SAN PABLO",
      "TUMBADEN"
    ],
    "SANTA CRUZ": [
      "ANDABAMBA",
      "CATACHE",
      "CHANCAYBAÑOS",
      "LA ESPERANZA",
      "NINABAMBA",
      "PULAN",
      "SANTA CRUZ",
      "SAUCEPAMPA",
      "SEXI",
      "UTICYACU",
      "YAUYUCAN"
    ]
  },
  "CALLAO": {
    "CALLAO": [
      "BELLAVISTA",
      "CALLAO",
      "CARMEN DE LA LEGUA REYNOSO",
      "LA PERLA",
      "LA PUNTA",
      "MI PERU",
      "VENTANILLA"
    ]
  },
  "CUSCO": {
    "ACOMAYO": [
      "ACOMAYO",
      "ACOPIA",
      "ACOS",
      "MOSOC LLACTA",
      "POMACANCHI",
      "RONDOCAN",
      "SANGARARA"
    ],
    "ANTA": [
      "ANCAHUASI",
      "ANTA",
      "CACHIMAYO",
      "CHINCHAYPUJIO",
      "HUAROCONDO",
      "LIMATAMBO",
      "MOLLEPATA",
      "PUCYURA",
      "ZURITE"
    ],
    "CALCA": [
      "CALCA",
      "COYA",
      "LAMAY",
      "LARES",
      "PISAC",
      "SAN SALVADOR",
      "TARAY",
      "YANATILE"
    ],
    "CANAS": [
      "CHECCA",
      "KUNTURKANKI",
      "LANGUI",
      "LAYO",
      "PAMPAMARCA",
      "QUEHUE",
      "TUPAC AMARU",
      "YANAOCA"
    ],
    "CANCHIS": [
      "CHECACUPE",
      "COMBAPATA",
      "MARANGANI",
      "PITUMARCA",
      "SAN PABLO",
      "SAN PEDRO",
      "SICUANI",
      "TINTA"
    ],
    "CHUMBIVILCAS": [
      "CAPACMARCA",
      "CHAMACA",
      "COLQUEMARCA",
      "LIVITACA",
      "LLUSCO",
      "QUIÑOTA",
      "SANTO TOMAS",
      "VELILLE"
    ],
    "CUSCO": [
      "CCORCA",
      "CUSCO",
      "POROY",
      "SAN JERONIMO",
      "SAN SEBASTIAN",
      "SANTIAGO",
      "SAYLLA",
      "WANCHAQ"
    ],
    "ESPINAR": [
      "ALTO PICHIGUA",
      "CONDOROMA",
      "COPORAQUE",
      "ESPINAR",
      "OCORURO",
      "PALLPATA",
      "PICHIGUA",
      "SUYCKUTAMBO"
    ],
    "LA CONVENCION": [
      "CIELO PUNCO",
      "ECHARATE",
      "HUAYOPATA",
      "INKAWASI",
      "KUMPIRUSHIATO",
      "MANITEA",
      "MARANURA",
      "MEGANTONI",
      "OCOBAMBA",
      "PICHARI",
      "QUELLOUNO",
      "QUIMBIRI",
      "SANTA ANA",
      "SANTA TERESA",
      "UNION ASHÁNINKA",
      "VILCABAMBA",
      "VILLA KINTIARINA",
      "VILLA VIRGEN"
    ],
    "PARURO": [
      "ACCHA",
      "CCAPI",
      "COLCHA",
      "HUANOQUITE",
      "OMACHA",
      "PACCARITAMBO",
      "PARURO",
      "PILLPINTO",
      "YAURISQUE"
    ],
    "PAUCARTAMBO": [
      "CAICAY",
      "CHALLABAMBA",
      "COLQUEPATA",
      "HUANCARANI",
      "KOSÑIPATA",
      "PAUCARTAMBO"
    ],
    "QUISPICANCHI": [
      "ANDAHUAYLILLAS",
      "CAMANTI",
      "CCARHUAYO",
      "CCATCA",
      "CUSIPATA",
      "HUARO",
      "LUCRE",
      "MARCAPATA",
      "OCONGATE",
      "OROPESA",
      "QUIQUIJANA",
      "URCOS"
    ],
    "URUBAMBA": [
      "CHINCHERO",
      "HUAYLLABAMBA",
      "MACHUPICCHU",
      "MARAS",
      "OLLANTAYTAMBO",
      "URUBAMBA",
      "YUCAY"
    ]
  },
  "HUANCAVELICA": {
    "ACOBAMBA": [
      "ACOBAMBA",
      "ANDABAMBA",
      "ANTA",
      "CAJA",
      "MARCAS",
      "PAUCARA",
      "POMACOCHA",
      "ROSARIO"
    ],
    "ANGARAES": [
      "ANCHONGA",
      "CALLANMARCA",
      "CCOCHACCASA",
      "CHINCHO",
      "CONGALLA",
      "HUANCA-HUANCA",
      "HUAYLLAY GRANDE",
      "JULCAMARCA",
      "LIRCAY",
      "SAN ANTONIO DE ANTAPARCO",
      "SANTO TOMAS DE PATA",
      "SECCLLA"
    ],
    "CASTROVIRREYNA": [
      "ARMA",
      "AURAHUA",
      "CAPILLAS",
      "CASTROVIRREYNA",
      "CHUPAMARCA",
      "COCAS",
      "HUACHOS",
      "HUAMATAMBO",
      "MOLLEPAMPA",
      "SAN JUAN",
      "SANTA ANA",
      "TANTARA",
      "TICRAPO"
    ],
    "CHURCAMPA": [
      "ANCO",
      "CHINCHIHUASI",
      "CHURCAMPA",
      "COSME",
      "EL CARMEN",
      "LA MERCED",
      "LOCROJA",
      "PACHAMARCA",
      "PAUCARBAMBA",
      "SAN MIGUEL DE MAYOCC",
      "SAN PEDRO DE CORIS"
    ],
    "HUANCAVELICA": [
      "ACOBAMBILLA",
      "ACORIA",
      "ASCENSION",
      "CONAYCA",
      "CUENCA",
      "HUACHOCOLPA",
      "HUANCAVELICA",
      "HUANDO",
      "HUAYLLAHUARA",
      "IZCUCHACA",
      "LARIA",
      "MANTA",
      "MARISCAL CACERES",
      "MOYA",
      "NUEVO OCCORO",
      "PALCA",
      "PILCHACA",
      "VILCA",
      "YAULI"
    ],
    "HUAYTARA": [
      "AYAVI",
      "CORDOVA",
      "HUAYACUNDO ARMA",
      "HUAYTARA",
      "LARAMARCA",
      "OCOYO",
      "PILPICHACA",
      "QUERCO",
      "QUITO-ARMA",
      "SAN ANTONIO DE CUSICANCHA",
      "SAN FRANCISCO DE SANGAYAICO",
      "SAN ISIDRO",
      "SANTIAGO DE CHOCORVOS",
      "SANTIAGO DE QUIRAHUARA",
      "SANTO DOMINGO DE CAPILLAS",
      "TAMBO"
    ],
    "TAYACAJA": [
      "ACOSTAMBO",
      "ACRAQUIA",
      "AHUAYCHA",
      "ANDAYMARCA",
      "COCHABAMBA",
      "COLCABAMBA",
      "DANIEL HERNANDEZ",
      "HUACHOCOLPA",
      "HUARIBAMBA",
      "LAMBRAS",
      "PAMPAS",
      "PAZOS",
      "PICHOS",
      "QUICHUAS",
      "QUISHUAR",
      "ROBLE",
      "SALCABAMBA",
      "SALCAHUASI",
      "SAN MARCOS DE ROCCHAC",
      "SANTIAGO DE TUCUMA",
      "SURCUBAMBA",
      "TINTAY PUNCU",
      "ÑAHUIMPUQUIO"
    ]
  },
  "HUANUCO": {
    "AMBO": [
      "AMBO",
      "CAYNA",
      "COLPAS",
      "CONCHAMARCA",
      "HUACAR",
      "SAN FRANCISCO",
      "SAN RAFAEL",
      "TOMAY KICHWA"
    ],
    "DOS DE MAYO": [
      "CHUQUIS",
      "LA UNION",
      "MARIAS",
      "PACHAS",
      "QUIVILLA",
      "RIPAN",
      "SHUNQUI",
      "SILLAPATA",
      "YANAS"
    ],
    "HUACAYBAMBA": [
      "CANCHABAMBA",
      "COCHABAMBA",
      "HUACAYBAMBA",
      "PINRA"
    ],
    "HUAMALIES": [
      "ARANCAY",
      "CHAVIN DE PARIARCA",
      "JACAS GRANDE",
      "JIRCAN",
      "LLATA",
      "MIRAFLORES",
      "MONZON",
      "PUNCHAO",
      "PUÑOS",
      "SINGA",
      "TANTAMAYO"
    ],
    "HUANUCO": [
      "AMARILIS",
      "CHINCHAO",
      "CHURUBAMBA",
      "HUANUCO",
      "MARGOS",
      "PILLCO MARCA",
      "QUISQUI",
      "SAN FRANCISCO DE CAYRAN",
      "SAN PABLO DE PILLAO",
      "SAN PEDRO DE CHAULAN",
      "SANTA MARIA DEL VALLE",
      "YACUS",
      "YARUMAYO"
    ],
    "LAURICOCHA": [
      "BAÑOS",
      "JESUS",
      "JIVIA",
      "QUEROPALCA",
      "RONDOS",
      "SAN FRANCISCO DE ASIS",
      "SAN MIGUEL DE CAURI"
    ],
    "LEONCIO PRADO": [
      "CASTILLO GRANDE",
      "DANIEL ALOMIAS ROBLES",
      "HERMILIO VALDIZAN",
      "JOSE CRESPO Y CASTILLO",
      "LUYANDO",
      "MARIANO DAMASO BERAUN",
      "PUCAYACU",
      "PUEBLO NUEVO",
      "RUPA-RUPA",
      "SANTO DOMINGO DE ANDA"
    ],
    "MARAÑON": [
      "CHOLON",
      "HUACRACHUCO",
      "LA MORADA",
      "SAN BUENAVENTURA",
      "SANTA ROSA DE ALTO YANAJANCA"
    ],
    "PACHITEA": [
      "CHAGLLA",
      "MOLINO",
      "PANAO",
      "UMARI"
    ],
    "PUERTO INCA": [
      "CODO DEL POZUZO",
      "HONORIA",
      "PUERTO INCA",
      "TOURNAVISTA",
      "YUYAPICHIS"
    ],
    "YAROWILCA": [
      "APARICIO POMARES",
      "CAHUAC",
      "CHACABAMBA",
      "CHAVINILLO",
      "CHORAS",
      "JACAS CHICO",
      "OBAS",
      "PAMPAMARCA"
    ]
  },
  "ICA": {
    "CHINCHA": [
      "ALTO LARAN",
      "CHAVIN",
      "CHINCHA ALTA",
      "CHINCHA BAJA",
      "EL CARMEN",
      "GROCIO PRADO",
      "PUEBLO NUEVO",
      "SAN JUAN DE YANAC",
      "SAN PEDRO DE HUACARPANA",
      "SUNAMPE",
      "TAMBO DE MORA"
    ],
    "ICA": [
      "ICA",
      "LA TINGUIÑA",
      "LOS AQUIJES",
      "OCUCAJE",
      "PACHACUTEC",
      "PARCONA",
      "PUEBLO NUEVO",
      "SALAS",
      "SAN JOSE DE LOS MOLINOS",
      "SAN JUAN BAUTISTA",
      "SANTIAGO",
      "SUBTANJALLA",
      "TATE",
      "YAUCA DEL ROSARIO"
    ],
    "NAZCA": [
      "CHANGUILLO",
      "EL INGENIO",
      "MARCONA",
      "NAZCA",
      "VISTA ALEGRE"
    ],
    "PALPA": [
      "LLIPATA",
      "PALPA",
      "RIO GRANDE",
      "SANTA CRUZ",
      "TIBILLO"
    ],
    "PISCO": [
      "HUANCANO",
      "HUMAY",
      "INDEPENDENCIA",
      "PARACAS",
      "PISCO",
      "SAN ANDRES",
      "SAN CLEMENTE",
      "TUPAC AMARU INCA"
    ]
  },
  "JUNIN": {
    "CHANCHAMAYO": [
      "CHANCHAMAYO",
      "PERENE",
      "PICHANAQUI",
      "SAN LUIS DE SHUARO",
      "SAN RAMON",
      "VITOC"
    ],
    "CHUPACA": [
      "AHUAC",
      "CHONGOS BAJO",
      "CHUPACA",
      "HUACHAC",
      "HUAMANCACA CHICO",
      "SAN JUAN DE JARPA",
      "SAN JUAN DE YSCOS",
      "TRES DE DICIEMBRE",
      "YANACANCHA"
    ],
    "CONCEPCION": [
      "ACO",
      "ANDAMARCA",
      "CHAMBARA",
      "COCHAS",
      "COMAS",
      "CONCEPCION",
      "HEROINAS TOLEDO",
      "MANZANARES",
      "MARISCAL CASTILLA",
      "MATAHUASI",
      "MITO",
      "NUEVE DE JULIO",
      "ORCOTUNA",
      "SAN JOSE DE QUERO",
      "SANTA ROSA DE OCOPA"
    ],
    "HUANCAYO": [
      "CARHUACALLANGA",
      "CHACAPAMPA",
      "CHICCHE",
      "CHILCA",
      "CHONGOS ALTO",
      "CHUPURO",
      "COLCA",
      "CULLHUAS",
      "EL TAMBO",
      "HUACRAPUQUIO",
      "HUALHUAS",
      "HUANCAN",
      "HUANCAYO",
      "HUASICANCHA",
      "HUAYUCACHI",
      "INGENIO",
      "PARIAHUANCA",
      "PILCOMAYO",
      "PUCARA",
      "QUICHUAY",
      "QUILCAS",
      "SAN AGUSTIN",
      "SAN JERONIMO DE TUNAN",
      "SANTO DOMINGO DE ACOBAMBA",
      "SAPALLANGA",
      "SAÑO",
      "SICAYA",
      "VIQUES"
    ],
    "JAUJA": [
      "ACOLLA",
      "APATA",
      "ATAURA",
      "CANCHAYLLO",
      "CURICACA",
      "EL MANTARO",
      "HUAMALI",
      "HUARIPAMPA",
      "HUERTAS",
      "JANJAILLO",
      "JAUJA",
      "JULCAN",
      "LEONOR ORDOÑEZ",
      "LLOCLLAPAMPA",
      "MARCO",
      "MASMA",
      "MASMA CHICCHE",
      "MOLINOS",
      "MONOBAMBA",
      "MUQUI",
      "MUQUIYAUYO",
      "PACA",
      "PACCHA",
      "PANCAN",
      "PARCO",
      "POMACANCHA",
      "RICRAN",
      "SAN LORENZO",
      "SAN PEDRO DE CHUNAN",
      "SAUSA",
      "SINCOS",
      "TUNAN MARCA",
      "YAULI",
      "YAUYOS"
    ],
    "JUNIN": [
      "CARHUAMAYO",
      "JUNIN",
      "ONDORES",
      "ULCUMAYO"
    ],
    "SATIPO": [
      "COVIRIALI",
      "LLAYLLA",
      "MAZAMARI",
      "PAMPA HERMOSA",
      "PANGOA",
      "RIO NEGRO",
      "RIO TAMBO",
      "SATIPO",
      "VIZCATAN DEL ENE"
    ],
    "TARMA": [
      "ACOBAMBA",
      "HUARICOLCA",
      "HUASAHUASI",
      "LA UNION",
      "PALCA",
      "PALCAMAYO",
      "SAN PEDRO DE CAJAS",
      "TAPO",
      "TARMA"
    ],
    "YAULI": [
      "CHACAPALPA",
      "HUAY-HUAY",
      "LA OROYA",
      "MARCAPOMACOCHA",
      "MOROCOCHA",
      "PACCHA",
      "SANTA BARBARA DE CARHUACAYAN",
      "SANTA ROSA DE SACCO",
      "SUITUCANCHA",
      "YAULI"
    ]
  },
  "LA LIBERTAD": {
    "ASCOPE": [
      "ASCOPE",
      "CASA GRANDE",
      "CHICAMA",
      "CHOCOPE",
      "MAGDALENA DE CAO",
      "PAIJAN",
      "RAZURI",
      "SANTIAGO DE CAO"
    ],
    "BOLIVAR": [
      "BAMBAMARCA",
      "BOLIVAR",
      "CONDORMARCA",
      "LONGOTEA",
      "UCHUMARCA",
      "UCUNCHA"
    ],
    "CHEPEN": [
      "CHEPEN",
      "PACANGA",
      "PUEBLO NUEVO"
    ],
    "GRAN CHIMU": [
      "CASCAS",
      "LUCMA",
      "MARMOT",
      "SAYAPULLO"
    ],
    "JULCAN": [
      "CALAMARCA",
      "CARABAMBA",
      "HUASO",
      "JULCAN"
    ],
    "OTUZCO": [
      "AGALLPAMPA",
      "CHARAT",
      "HUARANCHAL",
      "LA CUESTA",
      "MACHE",
      "OTUZCO",
      "PARANDAY",
      "SALPO",
      "SINSICAP",
      "USQUIL"
    ],
    "PACASMAYO": [
      "GUADALUPE",
      "JEQUETEPEQUE",
      "PACASMAYO",
      "SAN JOSE",
      "SAN PEDRO DE LLOC"
    ],
    "PATAZ": [
      "BULDIBUYO",
      "CHILLIA",
      "HUANCASPATA",
      "HUAYLILLAS",
      "HUAYO",
      "ONGON",
      "PARCOY",
      "PATAZ",
      "PIAS",
      "SANTIAGO DE CHALLAS",
      "TAURIJA",
      "TAYABAMBA",
      "URPAY"
    ],
    "SANCHEZ CARRION": [
      "CHUGAY",
      "COCHORCO",
      "CURGOS",
      "HUAMACHUCO",
      "MARCABAL",
      "SANAGORAN",
      "SARIN",
      "SARTIMBAMBA"
    ],
    "SANTIAGO DE CHUCO": [
      "ANGASMARCA",
      "CACHICADAN",
      "MOLLEBAMBA",
      "MOLLEPATA",
      "QUIRUVILCA",
      "SANTA CRUZ DE CHUCA",
      "SANTIAGO DE CHUCO",
      "SITABAMBA"
    ],
    "TRUJILLO": [
      "EL PORVENIR",
      "FLORENCIA DE MORA",
      "HUANCHACO",
      "LA ESPERANZA",
      "LAREDO",
      "MOCHE",
      "POROTO",
      "SALAVERRY",
      "SIMBAL",
      "TRUJILLO",
      "VICTOR LARCO HERRERA"
    ],
    "VIRU": [
      "CHAO",
      "GUADALUPITO",
      "VIRU"
    ]
  },
  "LAMBAYEQUE": {
    "CHICLAYO": [
      "CAYALTI",
      "CHICLAYO",
      "CHONGOYAPE",
      "ETEN",
      "ETEN PUERTO",
      "JOSE LEONARDO ORTIZ",
      "LA VICTORIA",
      "LAGUNAS",
      "MONSEFU",
      "NUEVA ARICA",
      "OYOTUN",
      "PATAPO",
      "PICSI",
      "PIMENTEL",
      "POMALCA",
      "PUCALA",
      "REQUE",
      "SANTA ROSA",
      "SAÑA",
      "TUMAN"
    ],
    "FERREÑAFE": [
      "CAÑARIS",
      "FERREÑAFE",
      "INCAHUASI",
      "MANUEL ANTONIO MESONES MURO",
      "PITIPO",
      "PUEBLO NUEVO"
    ],
    "LAMBAYEQUE": [
      "CHOCHOPE",
      "ILLIMO",
      "JAYANCA",
      "LAMBAYEQUE",
      "MOCHUMI",
      "MORROPE",
      "MOTUPE",
      "OLMOS",
      "PACORA",
      "SALAS",
      "SAN JOSE",
      "TUCUME"
    ]
  },
  "LIMA": {
    "BARRANCA": [
      "BARRANCA",
      "PARAMONGA",
      "PATIVILCA",
      "SUPE",
      "SUPE PUERTO"
    ],
    "CAJATAMBO": [
      "CAJATAMBO",
      "COPA",
      "GORGOR",
      "HUANCAPON",
      "MANAS"
    ],
    "CANTA": [
      "ARAHUAY",
      "CANTA",
      "HUAMANTANGA",
      "HUAROS",
      "LACHAQUI",
      "SAN BUENAVENTURA",
      "SANTA ROSA DE QUIVES"
    ],
    "CAÑETE": [
      "ASIA",
      "CALANGO",
      "CERRO AZUL",
      "CHILCA",
      "COAYLLO",
      "IMPERIAL",
      "LUNAHUANA",
      "MALA",
      "NUEVO IMPERIAL",
      "PACARAN",
      "QUILMANA",
      "SAN ANTONIO",
      "SAN LUIS",
      "SAN VICENTE DE CAÑETE",
      "SANTA CRUZ DE FLORES",
      "ZUÑIGA"
    ],
    "HUARAL": [
      "ATAVILLOS ALTO",
      "ATAVILLOS BAJO",
      "AUCALLAMA",
      "CHANCAY",
      "HUARAL",
      "IHUARI",
      "LAMPIAN",
      "PACARAOS",
      "SAN MIGUEL DE ACOS",
      "SANTA CRUZ DE ANDAMARCA",
      "SUMBILCA",
      "VEINTISIETE DE NOVIEMBRE"
    ],
    "HUAROCHIRI": [
      "ANTIOQUIA",
      "CALLAHUANCA",
      "CARAMPOMA",
      "CHICLA",
      "CUENCA",
      "HUACHUPAMPA",
      "HUANZA",
      "HUAROCHIRI",
      "LAHUAYTAMBO",
      "LANGA",
      "LARAOS",
      "MARIATANA",
      "MATUCANA",
      "RICARDO PALMA",
      "SAN ANDRES DE TUPICOCHA",
      "SAN ANTONIO",
      "SAN BARTOLOME",
      "SAN DAMIAN",
      "SAN JUAN DE IRIS",
      "SAN JUAN DE TANTARANCHE",
      "SAN LORENZO DE QUINTI",
      "SAN MATEO",
      "SAN MATEO DE OTAO",
      "SAN PEDRO DE CASTA",
      "SAN PEDRO DE HUANCAYRE",
      "SANGALLAYA",
      "SANTA CRUZ DE COCACHACRA",
      "SANTA EULALIA",
      "SANTIAGO DE ANCHUCAYA",
      "SANTIAGO DE TUNA",
      "SANTO DOMINGO DE LOS OLLEROS",
      "SURCO"
    ],
    "HUAURA": [
      "AMBAR",
      "CALETA DE CARQUIN",
      "CHECRAS",
      "HUACHO",
      "HUALMAY",
      "HUAURA",
      "LEONCIO PRADO",
      "PACCHO",
      "SANTA LEONOR",
      "SANTA MARIA",
      "SAYAN",
      "VEGUETA"
    ],
    "LIMA": [
      "ANCON",
      "ATE",
      "BARRANCO",
      "BREÑA",
      "CARABAYLLO",
      "CHACLACAYO",
      "CHORRILLOS",
      "CIENEGUILLA",
      "COMAS",
      "EL AGUSTINO",
      "INDEPENDENCIA",
      "JESUS MARIA",
      "LA MOLINA",
      "LA VICTORIA",
      "LIMA",
      "LINCE",
      "LOS OLIVOS",
      "LURIGANCHO",
      "LURIN",
      "MAGDALENA DEL MAR",
      "MIRAFLORES",
      "PACHACAMAC",
      "PUCUSANA",
      "PUEBLO LIBRE",
      "PUENTE PIEDRA",
      "PUNTA HERMOSA",
      "PUNTA NEGRA",
      "RIMAC",
      "SAN BARTOLO",
      "SAN BORJA",
      "SAN ISIDRO",
      "SAN JUAN DE LURIGANCHO",
      "SAN JUAN DE MIRAFLORES",
      "SAN LUIS",
      "SAN MARTIN DE PORRES",
      "SAN MIGUEL",
      "SANTA ANITA",
      "SANTA MARIA DE HUACHIPA",
      "SANTA MARIA DEL MAR",
      "SANTA ROSA",
      "SANTIAGO DE SURCO",
      "SURQUILLO",
      "VILLA EL SALVADOR",
      "VILLA MARIA DEL TRIUNFO"
    ],
    "OYON": [
      "ANDAJES",
      "CAUJUL",
      "COCHAMARCA",
      "NAVAN",
      "OYON",
      "PACHANGARA"
    ],
    "YAUYOS": [
      "ALIS",
      "AYAUCA",
      "AYAVIRI",
      "AZANGARO",
      "CACRA",
      "CARANIA",
      "CATAHUASI",
      "CHOCOS",
      "COCHAS",
      "COLONIA",
      "HONGOS",
      "HUAMPARA",
      "HUANCAYA",
      "HUANGASCAR",
      "HUANTAN",
      "HUAÑEC",
      "LARAOS",
      "LINCHA",
      "MADEAN",
      "MIRAFLORES",
      "OMAS",
      "PUTINZA",
      "QUINCHES",
      "QUINOCAY",
      "SAN JOAQUIN",
      "SAN PEDRO DE PILAS",
      "TANTA",
      "TAURIPAMPA",
      "TOMAS",
      "TUPE",
      "VITIS",
      "VIÑAC",
      "YAUYOS"
    ]
  },
  "LORETO": {
    "ALTO AMAZONAS": [
      "BALSAPUERTO",
      "JEBEROS",
      "LAGUNAS",
      "SANTA CRUZ",
      "TENIENTE CESAR LOPEZ ROJAS",
      "YURIMAGUAS"
    ],
    "DATEM DEL MARAÑON": [
      "ANDOAS",
      "BARRANCA",
      "CAHUAPANAS",
      "MANSERICHE",
      "MORONA",
      "PASTAZA"
    ],
    "LORETO": [
      "NAUTA",
      "PARINARI",
      "TIGRE",
      "TROMPETEROS",
      "URARINAS"
    ],
    "MARISCAL RAMON CASTILLA": [
      "PEBAS",
      "RAMON CASTILLA",
      "SAN PABLO",
      "YAVARI"
    ],
    "MAYNAS": [
      "ALTO NANAY",
      "BELEN",
      "FERNANDO LORES",
      "INDIANA",
      "IQUITOS",
      "LAS AMAZONAS",
      "MAZAN",
      "NAPO",
      "PUNCHANA",
      "PUTUMAYO",
      "SAN JUAN BAUTISTA",
      "TENIENTE MANUEL CLAVERO",
      "TORRES CAUSANA"
    ],
    "PUTUMAYO": [
      "PUTUMAYO",
      "ROSA PANDURO",
      "TENIENTE MANUEL CLAVERO",
      "YAGUAS"
    ],
    "REQUENA": [
      "ALTO TAPICHE",
      "CAPELO",
      "EMILIO SAN MARTIN",
      "JENARO HERRERA",
      "MAQUIA",
      "PUINAHUA",
      "REQUENA",
      "SAQUENA",
      "SOPLIN",
      "TAPICHE",
      "YAQUERANA"
    ],
    "UCAYALI": [
      "CONTAMANA",
      "INAHUAYA",
      "PADRE MARQUEZ",
      "PAMPA HERMOSA",
      "SARAYACU",
      "VARGAS GUERRA"
    ]
  },
  "MADRE DE DIOS": {
    "MANU": [
      "FITZCARRALD",
      "HUEPETUHE",
      "MADRE DE DIOS",
      "MANU"
    ],
    "TAHUAMANU": [
      "IBERIA",
      "IÑAPARI",
      "TAHUAMANU"
    ],
    "TAMBOPATA": [
      "INAMBARI",
      "LABERINTO",
      "LAS PIEDRAS",
      "TAMBOPATA"
    ]
  },
  "MOQUEGUA": {
    "GENERAL SANCHEZ CERRO": [
      "CHOJATA",
      "COALAQUE",
      "ICHUÑA",
      "LA CAPILLA",
      "LLOQUE",
      "MATALAQUE",
      "OMATE",
      "PUQUINA",
      "QUINISTAQUILLAS",
      "UBINAS",
      "YUNGA"
    ],
    "ILO": [
      "EL ALGARROBAL",
      "ILO",
      "PACOCHA"
    ],
    "MARISCAL NIETO": [
      "CARUMAS",
      "CUCHUMBAYA",
      "MOQUEGUA",
      "SAMEGUA",
      "SAN ANTONIO",
      "SAN CRISTOBAL",
      "TORATA"
    ]
  },
  "PASCO": {
    "DANIEL ALCIDES CARRION": [
      "CHACAYAN",
      "GOYLLARISQUIZGA",
      "PAUCAR",
      "SAN PEDRO DE PILLAO",
      "SANTA ANA DE TUSI",
      "TAPUC",
      "VILCABAMBA",
      "YANAHUANCA"
    ],
    "OXAPAMPA": [
      "CHONTABAMBA",
      "CONSTITUCION",
      "HUANCABAMBA",
      "OXAPAMPA",
      "PALCAZU",
      "POZUZO",
      "PUERTO BERMUDEZ",
      "VILLA RICA"
    ],
    "PASCO": [
      "CHAUPIMARCA",
      "HUACHON",
      "HUARIACA",
      "HUAYLLAY",
      "NINACACA",
      "PALLANCHACRA",
      "PAUCARTAMBO",
      "SAN FRANCISCO DE ASIS DE YARUSYACAN",
      "SIMON BOLIVAR",
      "TICLACAYAN",
      "TINYAHUARCO",
      "VICCO",
      "YANACANCHA"
    ]
  },
  "PIURA": {
    "AYABACA": [
      "AYABACA",
      "FRIAS",
      "JILILI",
      "LAGUNAS",
      "MONTERO",
      "PACAIPAMPA",
      "PAIMAS",
      "SAPILLICA",
      "SICCHEZ",
      "SUYO"
    ],
    "HUANCABAMBA": [
      "CANCHAQUE",
      "EL CARMEN DE LA FRONTERA",
      "HUANCABAMBA",
      "HUARMACA",
      "LALAQUIZ",
      "SAN MIGUEL DE EL FAIQUE",
      "SONDOR",
      "SONDORILLO"
    ],
    "MORROPON": [
      "BUENOS AIRES",
      "CHALACO",
      "CHULUCANAS",
      "LA MATANZA",
      "MORROPON",
      "SALITRAL",
      "SAN JUAN DE BIGOTE",
      "SANTA CATALINA DE MOSSA",
      "SANTO DOMINGO",
      "YAMANGO"
    ],
    "PAITA": [
      "AMOTAPE",
      "ARENAL",
      "COLAN",
      "LA HUACA",
      "PAITA",
      "TAMARINDO",
      "VICHAYAL"
    ],
    "PIURA": [
      "CASTILLA",
      "CATACAOS",
      "CURA MORI",
      "EL TALLAN",
      "LA ARENA",
      "LA UNION",
      "LAS LOMAS",
      "PIURA",
      "TAMBO GRANDE",
      "VEINTISEIS DE OCTUBRE"
    ],
    "SECHURA": [
      "BELLAVISTA DE LA UNION",
      "BERNAL",
      "CRISTO NOS VALGA",
      "RINCONADA LLICUAR",
      "SECHURA",
      "VICE"
    ],
    "SULLANA": [
      "BELLAVISTA",
      "IGNACIO ESCUDERO",
      "LANCONES",
      "MARCAVELICA",
      "MIGUEL CHECA",
      "QUERECOTILLO",
      "SALITRAL",
      "SULLANA"
    ],
    "TALARA": [
      "EL ALTO",
      "LA BREA",
      "LOBITOS",
      "LOS ORGANOS",
      "MANCORA",
      "PARIÑAS"
    ]
  },
  "PUNO": {
    "AZANGARO": [
      "ACHAYA",
      "ARAPA",
      "ASILLO",
      "AZANGARO",
      "CAMINACA",
      "CHUPA",
      "JOSE DOMINGO CHOQUEHUANCA",
      "MUÑANI",
      "POTONI",
      "SAMAN",
      "SAN ANTON",
      "SAN JOSE",
      "SAN JUAN DE SALINAS",
      "SANTIAGO DE PUPUJA",
      "TIRAPATA"
    ],
    "CARABAYA": [
      "AJOYANI",
      "AYAPATA",
      "COASA",
      "CORANI",
      "CRUCERO",
      "ITUATA",
      "MACUSANI",
      "OLLACHEA",
      "SAN GABAN",
      "USICAYOS"
    ],
    "CHUCUITO": [
      "DESAGUADERO",
      "HUACULLANI",
      "JULI",
      "KELLUYO",
      "PISACOMA",
      "POMATA",
      "ZEPITA"
    ],
    "EL COLLAO": [
      "CAPAZO",
      "CONDURIRI",
      "ILAVE",
      "PILCUYO",
      "SANTA ROSA"
    ],
    "HUANCANE": [
      "COJATA",
      "HUANCANE",
      "HUATASANI",
      "INCHUPALLA",
      "PUSI",
      "ROSASPATA",
      "TARACO",
      "VILQUE CHICO"
    ],
    "LAMPA": [
      "CABANILLA",
      "CALAPUJA",
      "LAMPA",
      "NICASIO",
      "OCUVIRI",
      "PALCA",
      "PARATIA",
      "PUCARA",
      "SANTA LUCIA",
      "VILAVILA"
    ],
    "MELGAR": [
      "ANTAUTA",
      "AYAVIRI",
      "CUPI",
      "LLALLI",
      "MACARI",
      "NUÑOA",
      "ORURILLO",
      "SANTA ROSA",
      "UMACHIRI"
    ],
    "MOHO": [
      "CONIMA",
      "HUAYRAPATA",
      "MOHO",
      "TILALI"
    ],
    "PUNO": [
      "ACORA",
      "AMANTANI",
      "ATUNCOLLA",
      "CAPACHICA",
      "CHUCUITO",
      "COATA",
      "HUATA",
      "MAÑAZO",
      "PAUCARCOLLA",
      "PICHACANI",
      "PLATERIA",
      "PUNO",
      "SAN ANTONIO",
      "TIQUILLACA",
      "VILQUE"
    ],
    "SAN ANTONIO DE PUTINA": [
      "ANANEA",
      "PEDRO VILCA APAZA",
      "PUTINA",
      "QUILCAPUNCU",
      "SINA"
    ],
    "SAN ROMAN": [
      "CABANA",
      "CABANILLAS",
      "CARACOTO",
      "JULIACA",
      "SAN MIGUEL"
    ],
    "SANDIA": [
      "ALTO INAMBARI",
      "CUYOCUYO",
      "LIMBANI",
      "PATAMBUCO",
      "PHARA",
      "QUIACA",
      "SAN JUAN DEL ORO",
      "SAN PEDRO DE PUTINA PUNCO",
      "SANDIA",
      "YANAHUAYA"
    ],
    "YUNGUYO": [
      "ANAPIA",
      "COPANI",
      "CUTURAPI",
      "OLLARAYA",
      "TINICACHI",
      "UNICACHI",
      "YUNGUYO"
    ]
  },
  "SAN MARTIN": {
    "BELLAVISTA": [
      "ALTO BIAVO",
      "BAJO BIAVO",
      "BELLAVISTA",
      "HUALLAGA",
      "SAN PABLO",
      "SAN RAFAEL"
    ],
    "EL DORADO": [
      "AGUA BLANCA",
      "SAN JOSE DE SISA",
      "SAN MARTIN",
      "SANTA ROSA",
      "SHATOJA"
    ],
    "HUALLAGA": [
      "ALTO SAPOSOA",
      "EL ESLABON",
      "PISCOYACU",
      "SACANCHE",
      "SAPOSOA",
      "TINGO DE SAPOSOA"
    ],
    "LAMAS": [
      "ALONSO DE ALVARADO",
      "BARRANQUITA",
      "CAYNARACHI",
      "CUÑUMBUQUI",
      "LAMAS",
      "PINTO RECODO",
      "RUMISAPA",
      "SAN ROQUE DE CUMBAZA",
      "SHANAO",
      "TABALOSOS",
      "ZAPATERO"
    ],
    "MARISCAL CACERES": [
      "CAMPANILLA",
      "HUICUNGO",
      "JUANJUI",
      "PACHIZA",
      "PAJARILLO"
    ],
    "MOYOBAMBA": [
      "CALZADA",
      "HABANA",
      "JEPELACIO",
      "MOYOBAMBA",
      "SORITOR",
      "YANTALO"
    ],
    "PICOTA": [
      "BUENOS AIRES",
      "CASPISAPA",
      "PICOTA",
      "PILLUANA",
      "PUCACACA",
      "SAN CRISTOBAL",
      "SAN HILARION",
      "SHAMBOYACU",
      "TINGO DE PONASA",
      "TRES UNIDOS"
    ],
    "RIOJA": [
      "AWAJUN",
      "ELIAS SOPLIN VARGAS",
      "NUEVA CAJAMARCA",
      "PARDO MIGUEL",
      "POSIC",
      "RIOJA",
      "SAN FERNANDO",
      "YORONGOS",
      "YURACYACU"
    ],
    "SAN MARTIN": [
      "ALBERTO LEVEAU",
      "CACATACHI",
      "CHAZUTA",
      "CHIPURANA",
      "EL PORVENIR",
      "HUIMBAYOC",
      "JUAN GUERRA",
      "LA BANDA DE SHILCAYO",
      "MORALES",
      "PAPAPLAYA",
      "SAN ANTONIO",
      "SAUCE",
      "SHAPAJA",
      "TARAPOTO"
    ],
    "TOCACHE": [
      "NUEVO PROGRESO",
      "POLVORA",
      "SANTA LUCIA",
      "SHUNTE",
      "TOCACHE",
      "UCHIZA"
    ]
  },
  "TACNA": {
    "CANDARAVE": [
      "CAIRANI",
      "CAMILACA",
      "CANDARAVE",
      "CURIBAYA",
      "HUANUARA",
      "QUILAHUANI"
    ],
    "JORGE BASADRE": [
      "ILABAYA",
      "ITE",
      "LOCUMBA"
    ],
    "TACNA": [
      "ALTO DE LA ALIANZA",
      "CALANA",
      "CIUDAD NUEVA",
      "CORONEL GREGORIO ALBARRACIN LANCHIPA",
      "INCLAN",
      "LA YARADA LOS PALOS",
      "PACHIA",
      "PALCA",
      "POCOLLAY",
      "SAMA",
      "TACNA"
    ],
    "TARATA": [
      "ESTIQUE",
      "ESTIQUE-PAMPA",
      "HEROES ALBARRACIN CHUCATAMANI",
      "SITAJARA",
      "SUSAPAYA",
      "TARATA",
      "TARUCACHI",
      "TICACO"
    ]
  },
  "TUMBES": {
    "CONTRALMIRANTE VILLAR": [
      "CANOAS DE PUNTA SAL",
      "CASITAS",
      "ZORRITOS"
    ],
    "TUMBES": [
      "CORRALES",
      "LA CRUZ",
      "PAMPAS DE HOSPITAL",
      "SAN JACINTO",
      "SAN JUAN DE LA VIRGEN",
      "TUMBES"
    ],
    "ZARUMILLA": [
      "AGUAS VERDES",
      "MATAPALO",
      "PAPAYAL",
      "ZARUMILLA"
    ]
  },
  "UCAYALI": {
    "ATALAYA": [
      "RAYMONDI",
      "SEPAHUA",
      "TAHUANIA",
      "YURUA"
    ],
    "CORONEL PORTILLO": [
      "CALLERIA",
      "CAMPOVERDE",
      "IPARIA",
      "MANANTAY",
      "MASISEA",
      "NUEVA REQUENA",
      "YARINACOCHA"
    ],
    "PADRE ABAD": [
      "ALEXANDER VON HUMBOLDT",
      "BOQUERON",
      "CURIMANA",
      "HUIPOCA",
      "IRAZOLA",
      "NESHUYA",
      "PADRE ABAD"
    ],
    "PURUS": [
      "PURUS"
    ]
  }
};

export const REGIONS = [
  "AMAZONAS",
  "ANCASH",
  "APURIMAC",
  "AREQUIPA",
  "AYACUCHO",
  "CAJAMARCA",
  "CALLAO",
  "CUSCO",
  "HUANCAVELICA",
  "HUANUCO",
  "ICA",
  "JUNIN",
  "LA LIBERTAD",
  "LAMBAYEQUE",
  "LIMA",
  "LORETO",
  "MADRE DE DIOS",
  "MOQUEGUA",
  "PASCO",
  "PIURA",
  "PUNO",
  "SAN MARTIN",
  "TACNA",
  "TUMBES",
  "UCAYALI"
];
